version: '3'

vars:
  BACKEND_DIR: backend
  FRONTEND_DIR: frontend

tasks:
  dev:
    desc: Start everything (backend + frontend + database)
    cmds:
      - echo "🚀 Starting KeywordsChat..."
      - task: db-start
      - echo "🔧 Starting backend on http://localhost:8000"
      - cd {{.BACKEND_DIR}} && uvicorn app.main:app --reload --reload-delay 0.5 &
      - echo "🎨 Starting frontend on http://localhost:8080..."
      - echo "💡 Hot reload enabled - Press 'r' to reload, 'R' to restart"
      - cd {{.FRONTEND_DIR}} && flutter run -d chrome --web-port=8080

  dev-backend:
    desc: Start backend only with hot reload
    cmds:
      - task: db-start
      - echo "🔧 Starting backend on http://localhost:8000 with hot reload..."
      - cd {{.BACKEND_DIR}} && uvicorn app.main:app --reload --reload-delay 0.5

  dev-frontend:
    desc: Start frontend only with hot reload
    cmds:
      - echo "🎨 Starting frontend on http://localhost:8080 with hot reload..."
      - echo "💡 Press 'r' to hot reload or 'R' to hot restart"
      - cd {{.FRONTEND_DIR}} && flutter run -d chrome --web-port=8080

  setup:
    desc: First time setup - install dependencies and setup database
    cmds:
      - echo "📦 Installing dependencies..."
      - cd {{.BACKEND_DIR}} && pip install -r requirements.txt
      - cd {{.FRONTEND_DIR}} && flutter pub get
      - task: db-start
      - task: migrate

  db-start:
    desc: Start PostgreSQL database
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - docker-compose up -d db
      - sleep 3

  db-stop:
    desc: Stop PostgreSQL database
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - docker-compose stop db

  db-reset:
    desc: Reset database (WARNING - deletes all data)
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - docker-compose down -v
      - docker-compose up -d db
      - sleep 3
      - task: migrate

  migrate:
    desc: Run database migrations
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - alembic upgrade head

  clean:
    desc: Clean up - stop all services and remove caches
    cmds:
      - docker-compose -f {{.BACKEND_DIR}}/docker-compose.yml down
      - rm -rf {{.BACKEND_DIR}}/__pycache__
      - rm -rf {{.FRONTEND_DIR}}/build
      - rm -rf {{.FRONTEND_DIR}}/.dart_tool
