version: '3'

vars:
  BACKEND_DIR: backend
  FRONTEND_DIR: frontend

tasks:
  dev:
    desc: Start backend with hot reload on port 8000
    cmds:
      - task: db-start
      - lsof -ti:8000 | xargs kill -9 2>/dev/null || true
      - echo "Starting backend on http://localhost:8000"
      - echo "Backend hot-reloads on Python changes"
      - cd {{.BACKEND_DIR}} && uvicorn app.main:app --reload --reload-delay 0.5 --port 8000

  build:
    desc: Build frontend (run this after frontend changes)
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - echo "Building Flutter web app..."
      - flutter build web

  dev-frontend:
    desc: Start frontend dev server with hot reload on port 8080
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - echo "Starting Flutter dev server on http://localhost:8080"
      - echo "Frontend hot-reloads on Dart changes (press 'r' to reload, 'R' to restart)"
      - flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0

  dev-watch:
    desc: Auto-rebuild frontend on changes (requires watchexec)
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - echo "Watching for changes and auto-rebuilding..."
      - watchexec -w lib -w pubspec.yaml -e dart,yaml -- flutter build web

  setup:
    desc: First time setup - install dependencies and setup database
    cmds:
      - echo "Installing dependencies..."
      - cd {{.BACKEND_DIR}} && pip install -r requirements.txt
      - cd {{.FRONTEND_DIR}} && flutter pub get
      - task: db-start
      - task: migrate

  db-start:
    desc: Start PostgreSQL database
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - docker-compose up -d db
      - sleep 3

  db-stop:
    desc: Stop PostgreSQL database
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - docker-compose stop db

  db-reset:
    desc: Reset database (WARNING - deletes all data)
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - docker-compose down -v
      - docker-compose up -d db
      - sleep 3
      - task: migrate

  migrate:
    desc: Run database migrations
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - alembic upgrade head

  clean:
    desc: Clean up - stop all services and remove caches
    cmds:
      - docker-compose -f {{.BACKEND_DIR}}/docker-compose.yml down
      - rm -rf {{.BACKEND_DIR}}/__pycache__
      - rm -rf {{.FRONTEND_DIR}}/build
      - rm -rf {{.FRONTEND_DIR}}/.dart_tool

  preview:
    desc: Preview the landing page locally
    cmds:
      - echo "Opening landing page..."
      - open http://localhost:8000
      - echo "Landing page at http://localhost:8000"
      - echo "App at http://localhost:8000/app"
