"""add_project_and_scan_models

Revision ID: 21aca27478d6
Revises: 705126b332d7
Create Date: 2025-11-15 19:11:13.734953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aca27478d6'
down_revision = '705126b332d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('brand_terms', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('enabled_providers', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scan_frequency', sa.String(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_prompts', sa.Integer(), nullable=True),
    sa.Column('prompts_with_mention', sa.Integer(), nullable=True),
    sa.Column('providers_checked', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_table('visibility_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('provider_scores', sa.JSON(), nullable=True),
    sa.Column('total_prompts_tested', sa.Integer(), nullable=True),
    sa.Column('prompts_with_mention', sa.Integer(), nullable=True),
    sa.Column('mention_rate', sa.Float(), nullable=True),
    sa.Column('avg_mention_rank', sa.Float(), nullable=True),
    sa.Column('keywords_covered', sa.Integer(), nullable=True),
    sa.Column('keywords_total', sa.Integer(), nullable=True),
    sa.Column('score_change', sa.Float(), nullable=True),
    sa.Column('score_trend', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_scores_date'), 'visibility_scores', ['date'], unique=False)
    op.create_index(op.f('ix_visibility_scores_project_id'), 'visibility_scores', ['project_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_type', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('prompt_metadata', sa.JSON(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.Column('brand_found', sa.Boolean(), nullable=True),
    sa.Column('brand_mentions', sa.JSON(), nullable=True),
    sa.Column('mention_positions', sa.JSON(), nullable=True),
    sa.Column('context_snippets', sa.JSON(), nullable=True),
    sa.Column('mention_rank', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_provider'), 'scan_results', ['provider'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_id'), 'scan_results', ['scan_id'], unique=False)
    op.add_column('users', sa.Column('projects_limit', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('scans_per_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('scans_used_this_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('usage_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usage_reset_at')
    op.drop_column('users', 'scans_used_this_month')
    op.drop_column('users', 'scans_per_month')
    op.drop_column('users', 'projects_limit')
    op.drop_index(op.f('ix_scan_results_scan_id'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_provider'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_visibility_scores_project_id'), table_name='visibility_scores')
    op.drop_index(op.f('ix_visibility_scores_date'), table_name='visibility_scores')
    op.drop_table('visibility_scores')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###






