"""Add strategy and keyword tracking tables

Revision ID: 47ba49cefba2
Revises: fe6cf7bab06f
Create Date: 2025-10-31 10:42:09.681240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ba49cefba2'
down_revision = 'fe6cf7bab06f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('tracked_keywords',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('competition', sa.String(), nullable=True),
    sa.Column('target_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_keywords_strategy_id'), 'tracked_keywords', ['strategy_id'], unique=False)
    op.create_table('keyword_rankings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tracked_keyword_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tracked_keyword_id'], ['tracked_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_rankings_checked_at'), 'keyword_rankings', ['checked_at'], unique=False)
    op.create_index(op.f('ix_keyword_rankings_tracked_keyword_id'), 'keyword_rankings', ['tracked_keyword_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_rankings_tracked_keyword_id'), table_name='keyword_rankings')
    op.drop_index(op.f('ix_keyword_rankings_checked_at'), table_name='keyword_rankings')
    op.drop_table('keyword_rankings')
    op.drop_index(op.f('ix_tracked_keywords_strategy_id'), table_name='tracked_keywords')
    op.drop_table('tracked_keywords')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###

