"""Add SEO Agent tables

Revision ID: c20ff9124741
Revises: ac0e24efd7b6
Create Date: 2025-11-13 13:24:27.065743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c20ff9124741'
down_revision = 'ac0e24efd7b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_tone_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('tone_description', sa.Text(), nullable=True),
    sa.Column('analyzed_posts_count', sa.Integer(), nullable=True),
    sa.Column('sample_content', sa.Text(), nullable=True),
    sa.Column('tone_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_tone_profiles_project_id'), 'content_tone_profiles', ['project_id'], unique=True)
    op.create_table('project_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('cms_type', sa.String(), nullable=False),
    sa.Column('cms_url', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('connection_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_integrations_project_id'), 'project_integrations', ['project_id'], unique=False)
    op.create_table('generated_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('integration_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('target_keywords', sa.JSON(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_url', sa.String(), nullable=True),
    sa.Column('cms_post_id', sa.String(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('tone_profile_id', sa.String(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tone_profile_id'], ['content_tone_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_integration_id'), 'generated_content', ['integration_id'], unique=False)
    op.create_index(op.f('ix_generated_content_project_id'), 'generated_content', ['project_id'], unique=False)
    op.create_table('content_generation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('generated_content_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('input_params', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_content_id'], ['generated_content.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_generation_jobs_generated_content_id'), 'content_generation_jobs', ['generated_content_id'], unique=False)
    op.create_index(op.f('ix_content_generation_jobs_project_id'), 'content_generation_jobs', ['project_id'], unique=False)
    op.alter_column('pinned_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('pinned_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('technical_audits', 'full_audit_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_technical_audits_created'), table_name='technical_audits')
    op.drop_index(op.f('idx_technical_audits_project'), table_name='technical_audits')
    op.drop_constraint(op.f('fk_project'), 'technical_audits', type_='foreignkey')
    op.create_foreign_key(None, 'technical_audits', 'projects', ['project_id'], ['id'])
    op.alter_column('tracked_keywords', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('tracked_keywords', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'backlink_rows_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'backlink_rows_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'backlink_rows_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('users', 'backlink_rows_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tracked_keywords', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tracked_keywords', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.drop_constraint(None, 'technical_audits', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project'), 'technical_audits', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_technical_audits_project'), 'technical_audits', ['project_id'], unique=False)
    op.create_index(op.f('idx_technical_audits_created'), 'technical_audits', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('technical_audits', 'full_audit_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('pinned_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('pinned_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_content_generation_jobs_project_id'), table_name='content_generation_jobs')
    op.drop_index(op.f('ix_content_generation_jobs_generated_content_id'), table_name='content_generation_jobs')
    op.drop_table('content_generation_jobs')
    op.drop_index(op.f('ix_generated_content_project_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_integration_id'), table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index(op.f('ix_project_integrations_project_id'), table_name='project_integrations')
    op.drop_table('project_integrations')
    op.drop_index(op.f('ix_content_tone_profiles_project_id'), table_name='content_tone_profiles')
    op.drop_table('content_tone_profiles')
    # ### end Alembic commands ###






