"""Add strategy and keyword tracking tables

Revision ID: c406e98e41d5
Revises: fe6cf7bab06f
Create Date: 2025-10-31 10:34:53.586303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c406e98e41d5'
down_revision = 'fe6cf7bab06f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

